// <auto-generated />
using System;
using DuitkuMvpNetApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DuitkuMvpNetApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240814040417_CreateInitialSchema")]
    partial class CreateInitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DuitkuMvpNetApp.Models.Item", b =>
                {
                    b.Property<int>("MsItemsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MsItemsId"));

                    b.Property<double>("MsItemsHarga")
                        .HasColumnType("double");

                    b.Property<string>("MsItemsNama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MsItemsTransactionId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("MsItemsId");

                    b.HasIndex("MsItemsTransactionId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("DuitkuMvpNetApp.Models.Transaction", b =>
                {
                    b.Property<string>("MsTransactionId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MsTransactionDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("MsTransactionStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("MsTransactionTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("MsTransactionTotalAmount")
                        .HasColumnType("double");

                    b.HasKey("MsTransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("DuitkuMvpNetApp.Models.Item", b =>
                {
                    b.HasOne("DuitkuMvpNetApp.Models.Transaction", "Transaction")
                        .WithMany("Items")
                        .HasForeignKey("MsItemsTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("DuitkuMvpNetApp.Models.Transaction", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
